### PR TITLE
Add Graphics Gems I to CMakeLists.txt and fix all errors and warnings.

### PR DESCRIPTION
**Pull request by gonsolo**

### CODE REVIEW

**Comment by erich666** [comment]
Should I wait a few days until the code settles down?

**Comment by gonsolo** [comment]
>
> Should I wait a few days until the code settles down?
>

I just used one file but it is kind of addictive when you know there is
something unfinished. Honestly, I don't know, I might finish it or not...

-- 
g

**Comment by erich666** [comment]
Go for it - I know what you mean. No rush from my end, but I'd rather any fixes accumulate into one pull, so I'll grab this pull request in a few days (or more, if you wish).

**Comment by gonsolo** [comment]
>
> Go for it - I know what you mean. No rush from my end, but I'd rather any
> fixes accumulate into one pull, so I'll grab this pull request in a few
> days (or more, if you wish).
>

Ok. Done. I added all files for Gems 1 to 5 but didn't bother about
warnings. Everything compiles with VS2015. I think I'm done now.

-- 
g

P.S.: If somebody is interested in doing a Graphics Gems Revisisted Kindle
Edition with everything updated to modern C++ I'd be happy to help out. But
this would be a *lot* of work. :)

**Comment by gonsolo** [comment]
All errors and warnings fixed on Linux/OS X/Windows 10.

This should be it. :)

**Comment by erich666** [comment]
Thanks! Merged.

**Pull request merged**
